FROM balenalib/%%BALENA_MACHINE_NAME%%-node:11-buster-run

WORKDIR /usr/src/app

COPY package.json package.json

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*

COPY . ./


CMD ["npm", "start"]