version: "2"
services:
  mongo:
    build: ./mongo
    restart: always
    privileged: true
    network_mode: "host"
    ports:
      - "27017:27017"
  express:
    depends_on:
      - mongo
    build: ./express
    network_mode: "host"
    ports:
      - "3000:3000"
