
FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.7-buster-run

# Install packages
RUN pip3 install --upgrade \
	pymongo \
	request

# Set our working directory
WORKDIR /usr/src/app

# This will copy all files in our root to the working  directory in the container
COPY . ./

# main.py will run when container starts up on the device
CMD ["bash","start.sh"]